# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "obernardovieira"
    ignored_updates:
      - match:
          dependency_name: "jest"
          dependency_name: "web3"
          dependency_name: "typescript"
          dependency_name: "react-scripts"
          dependency_name: "ipfs"
          dependency_name: "orbit-db"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
